apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notif.fullname" . }}
  labels:
    {{- include "notif.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notif.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notif.labels" . | nindent 8 }}
    spec:
      # TODO : securityContext Pod-level.
      containers:
        - name: notif
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          env:
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
            - name: LOG_LEVEL
              value: "{{ .Values.env.LOG_LEVEL }}"
          # TODO : probes, resources, securityContext.
