apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devhub
  namespace: argocd
spec:
  description: Plateforme DevHub Campus
  sourceRepos:
    - https://github.com/valaack/devhub-campus.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: devhub-dev
    - server: https://kubernetes.default.svc
      namespace: devhub-preview-*
    - server: https://kubernetes.default.svc
      namespace: argocd
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
