image:
  repository: ghcr.io/<votre-handle>/planning
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: nginx
  host: planning.devhub.local
  path: /

env:
  LOG_LEVEL: info

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 200m
    memory: 192Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

probes:
  readiness:
    path: /healthz
    initialDelaySeconds: 3
    periodSeconds: 5
  liveness:
    path: /healthz
    initialDelaySeconds: 15
    periodSeconds: 10
